#!/usr/bin/env bash
# display information about passed in domain or subdomains.

function subdomain_check {
	dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
	awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

if [ $# -lt 1 ]
then
	echo "*** Provide domain name ***"
elif [ $# -eq 1 ]
then
	domain_check "$1";
else
	subdomain_check "$1" "$2";
fi
