#!/usr/bin/env bash
#Fixes Nginx container so that Nginx is running as the nginx user rather than the root user.

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Update the Nginx configuration to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

#Change user permissions
chmod 644 /etc/nginx/nginx.conf

#kill all process
pkill apache2

# Restart Nginx 
sudo -u nginx service nginx start
